version: '3'
services:
  node-app:
    container_name: express-app-container
    build: 
      context: ./backend/
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend/src:/app/src:ro
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - data-base
      - redis
    
  data-base:
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  react:
    container_name: react-app
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src:ro
    ports:
      - "3001:3000"
    depends_on:
      - node-app
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always




volumes:
  mongo_db: