version: '3'
services:
  node-app:
    container_name: express-app-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=doevelopment
    
    